- name: start other node
  block:
    - name: set galera config
      template:
        src: "galera_cnf.j2"
        dest: "/etc/mysql/conf.d/galera.cnf"
        mode: 0644
    - name: start galera cluster
      service:
        name: mariadb
        state: started
  when: ansible_hostname != "ubuntu1"